apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "56"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vit-api"},"name":"vit-api","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"vit-api"}},"template":{"metadata":{"labels":{"app":"vit-api"}},"spec":{"containers":[{"env":[{"name":"AWS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"aws_access_key_id","name":"aws-secrets"}}},{"name":"AWS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"aws_secret_access_key","name":"aws-secrets"}}},{"name":"REDIS_HOST","value":"redis-service"},{"name":"REDIS_PORT","value":"6379"}],"image":"087735574692.dkr.ecr.us-east-1.amazonaws.com/vit-torchscript:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":15,"periodSeconds":20,"timeoutSeconds":5},"name":"vit-api","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":10,"periodSeconds":5,"timeoutSeconds":3},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"512Mi"}}}]}}}}
    kubernetes.io/change-cause: kubectl set image deployment/vit-api vit-api=087735574692.dkr.ecr.us-east-1.amazonaws.com/vit-torchscript:latest
      --record=true
  creationTimestamp: "2025-02-21T11:47:14Z"
  generation: 58
  labels:
    app: vit-api
  name: vit-api
  namespace: default
  resourceVersion: "3619355"
  uid: 9829e75a-f2d3-491f-9d99-c338e27018e5
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vit-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-03-06T10:10:18Z"
      creationTimestamp: null
      labels:
        app: vit-api
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        image: 087735574692.dkr.ecr.us-east-1.amazonaws.com/vit-torchscript:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: vit-api
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vit-api-sa
      serviceAccountName: vit-api-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-03-06T09:51:08Z"
    lastUpdateTime: "2025-03-06T09:51:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-06T09:50:40Z"
    lastUpdateTime: "2025-03-06T10:15:08Z"
    message: ReplicaSet "vit-api-8d57dbc6c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 58
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
