apiVersion: apps/v1
kind: Deployment
metadata:
  name: vit-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vit-api
  template:
    metadata:
      labels:
        app: vit-api
    spec:
      containers:
      - name: vit-api
        image: 087735574692.dkr.ecr.us-east-1.amazonaws.com/vit-torchscript:latest
        imagePullPolicy: Always  # Ensures it always pulls the latest version
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:  # AWS Credentials and Redis Configuration
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_secret_access_key
        - name: REDIS_HOST
          value: "redis-service"  # Change if your Redis service name is different
        - name: REDIS_PORT
          value: "6379"
        readinessProbe:  # Readiness Probe
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:  # Liveness Probe
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vit-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: vit-api
