apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"vit-api","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"vit-api"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-02-19T07:22:06Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: vit-api
  namespace: default
  resourceVersion: "1928010"
  uid: 0152e554-85d3-4430-89df-fd6ceb622850
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.233.235
  clusterIPs:
  - 10.100.233.235
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30833
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: vit-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a0152e55485d3443089dffd6ceb62285-1593791318.us-east-1.elb.amazonaws.com
