name: Deploy ViT to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy to EKS
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Checkout the Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Amazon ECR using GitHub Action
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ secrets.EKS_REGION }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t vit-torchscript:latest .

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag vit-torchscript:latest ${{ secrets.ECR_REPOSITORY }}:latest

      # Push Docker Image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.EKS_REGION }}

      # Update Kubernetes Deployment on EKS
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.EKS_REGION }}
          kubectl apply -f vit-deployment.yaml
          kubectl set image deployment/vit-api vit-api=${{ secrets.ECR_REPOSITORY }}:latest
          kubectl rollout restart deployment vit-api
          kubectl rollout status deployment vit-api
